using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;


namespace CMS_App.Model
{
    public class Page
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        public string PageName { get; set; }

        public string PageTitle { get; set; }

        public string PageContent { get; set; }

        public string Image { get; set; }

    }
}
