using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace CMS_App.Model
{
    public class Post
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }
        public string PostState { get; set; }
        public string PostAuthor { get; set; } // Username
        public string PostImage { get; set; }
        public string PostContentBrief { get; set; }
        public string PostContentExtended { get; set; }
        public DateTime PostPublishedDate { get; set; } = DateTime.Now;
        public DateTime PostModifiedDate { get; set; }

    }
}
